# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Relay.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bRelay.proto\"I\n\x07Request\x12\x11\n\tinterface\x18\x01 \x01(\t\x12\r\n\x05money\x18\x02 \x01(\x05\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x10\n\x08WriteSet\x18\x04 \x03(\x05\"l\n\x08Response\x12\x11\n\tinterface\x18\x01 \x01(\t\x12\x0f\n\x07\x62\x61lance\x18\x02 \x01(\x05\x12\n\n\x02id\x18\x03 \x01(\x05\x12\x0e\n\x06\x62ranch\x18\x04 \x01(\x05\x12\x0e\n\x06result\x18\x05 \x01(\t\x12\x10\n\x08WriteSet\x18\x06 \x03(\x05\x32I\n\x06\x42ranch\x12\x1d\n\x04\x43\x61st\x12\x08.Request\x1a\t.Response\"\x00\x12 \n\x07\x44\x65liver\x12\x08.Request\x1a\t.Response\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Relay_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUEST']._serialized_start=15
  _globals['_REQUEST']._serialized_end=88
  _globals['_RESPONSE']._serialized_start=90
  _globals['_RESPONSE']._serialized_end=198
  _globals['_BRANCH']._serialized_start=200
  _globals['_BRANCH']._serialized_end=273
# @@protoc_insertion_point(module_scope)
